### PR TITLE
Add Singularity definition file and instructions

### PR DESCRIPTION
**Pull request by sloretz**
This adds a Singularity definition file that installs ROS Rolling + Drake + the demos in a Singularity container and adds instructions on how to use it.

@EricCousineau-TRI @IanTheEngineer FYI

### CODE REVIEW

**Review by EricCousineau-TRI — APPROVED** [review]
Sweet, thank you so much!!!

Some minor deviations:

- Just to be contrarian, I tried out building `singularity` in user space only. Seemed to work?
- I needed to `sudo apt install uidmap` on my host (not sure if it's related to above point)
- I like to put demo stuff in a tempdir, e.g. preceding with `cd $(mktemp -d)` and doing stuff in there
- I used the `singularity shell --containall --env DISPLAY=:1 --nv ...` to try and be uber minimal
- and that worked!

I did get the following warnings, but mebbe that's just 'cause I went off the beaten path?
```
WARNING: Disabling --writable-tmpfs as it can't be used in conjunction with underlay
WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (713) bind mounts
```

Here are my steps:
https://gist.github.com/EricCousineau-TRI/0a9fa209eb77acfdbb211a97afb52d3a

**Comment by EricCousineau-TRI** [comment]
Hm... at least with the setup that I did, I can only sometimes get `rviz2` and `ros2_demo.py` to talk (when restarting).

I see some weird behavior when I try restarting these scripts:
https://gist.github.com/EricCousineau-TRI/0a9fa209eb77acfdbb211a97afb52d3a/58c99dc8c04f0bd3b4a267559c5b86ae7ec2cb8f#file-steps-sh-L30-L36

See the video here: \
https://drakedevelopers.slack.com/archives/C01B5B320QY/p1607120331184700

**Comment by sloretz** [comment]
> * Just to be contrarian, I tried out building singularity in user space only. Seemed to work?
> * I needed to sudo apt install uidmap on my host (not sure if it's related to above point)

Seems related (https://github.com/singularityhub/singularity-docker/issues/9). It looks like the docs say for non-setuid installations ["Fakeroot functionality will rely on external setuid root `newuidmap` and `newgidmap` binaries which may be provided by the distribution"](https://sylabs.io/guides/3.7/admin-guide/user_namespace.html#unprivileged-installations), and both of these appear in the [list of files provided by the `uidmap` debian package](https://packages.debian.org/sid/amd64/uidmap/filelist).

> I like to put demo stuff in a tempdir, e.g. preceding with cd $(mktemp -d) and doing stuff in there

As in, the sandbox is in a tempdir?

> I used the singularity shell --containall --env DISPLAY=:1 --nv ... to try and be uber minimal

Yeah, makes sense with containers, though maybe not as important with Singularity. IIUC Docker does all it's work in a daemon run as `root`, so it restricts a container's access as much as possible to avoid giving it root access on the host. In contrast, Singularity containers run as the user that invoked it, so it defaults to granting everything the user has access to.

> WARNING: Disabling --writable-tmpfs as it can't be used in conjunction with underlay
> WARNING: underlay of /usr/bin/nvidia-smi required more than 50 (713) bind mounts

I haven't seen these before. What command outputs them?

**Comment by sloretz** [comment]
I'll merge this as is and investigate the startup behavior separately.

**Pull request merged**
